trigger:
- main

pool:
  name: Default

variables:
  MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
    path: $(MAVEN_CACHE_FOLDER)
  displayName: 'Restore Maven Cache'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-B'
    publishJUnitResults: false
  displayName: 'Build Java Project'
