trigger:
- main

pool:
  name: Default

steps:
- script: mvn clean install
  displayName: 'Build and run tests using Maven'
  workingDirectory: 'src'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Java Unit Tests'
  condition: succeededOrFailed()
