trigger:
- main

pool:
  name: Default  # Self-hosted agent pool

variables:
  mavenCacheFolder: '$(UserProfile)\.m2\repository'

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
    path: $(mavenCacheFolder)
  displayName: 'Restore Maven Cache'

- script: mvn clean install
  displayName: 'Build Project with Maven'

- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: $(mavenCacheFolder)
  displayName: 'Save Maven Cache'
  condition: succeeded()
